[2022-03-24 15:42:39,410] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: census_consumer_complaint.RemoteZipCsvExampleGen scheduled__2022-03-23T00:00:00+00:00 [queued]>
[2022-03-24 15:42:39,418] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: census_consumer_complaint.RemoteZipCsvExampleGen scheduled__2022-03-23T00:00:00+00:00 [queued]>
[2022-03-24 15:42:39,418] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-24 15:42:39,418] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-03-24 15:42:39,418] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-24 15:42:39,428] {taskinstance.py:1264} INFO - Executing <Task(AirflowComponent): RemoteZipCsvExampleGen> on 2022-03-23 00:00:00+00:00
[2022-03-24 15:42:39,441] {standard_task_runner.py:52} INFO - Started process 230 to run task
[2022-03-24 15:42:39,443] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'census_consumer_complaint', 'RemoteZipCsvExampleGen', 'scheduled__2022-03-23T00:00:00+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/census_consumer_complaint.py', '--cfg-path', '/tmp/tmp7fuoqwq0', '--error-file', '/tmp/tmpys7zbf_5']
[2022-03-24 15:42:39,444] {standard_task_runner.py:77} INFO - Job 54: Subtask RemoteZipCsvExampleGen
[2022-03-24 15:42:39,480] {logging_mixin.py:109} INFO - Running <TaskInstance: census_consumer_complaint.RemoteZipCsvExampleGen scheduled__2022-03-23T00:00:00+00:00 [running]> on host 691464fec4e5
[2022-03-24 15:42:39,517] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=census_consumer_complaint
AIRFLOW_CTX_TASK_ID=RemoteZipCsvExampleGen
AIRFLOW_CTX_EXECUTION_DATE=2022-03-23T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-23T00:00:00+00:00
[2022-03-24 15:42:39,518] {base_component_launcher.py:190} INFO - Running driver for RemoteZipCsvExampleGen
[2022-03-24 15:42:39,522] {metadata_store.py:101} INFO - MetadataStore with DB connection initialized
[2022-03-24 15:42:39,523] {utils.py:698} INFO - select span and version = (0, None)
[2022-03-24 15:42:39,523] {utils.py:707} INFO - latest span and version = (0, None)
[2022-03-24 15:42:39,538] {base_component_launcher.py:196} INFO - Running executor for RemoteZipCsvExampleGen
[2022-03-24 15:42:39,540] {base_example_gen_executor.py:272} INFO - Generating examples.
[2022-03-24 15:42:39,541] {pipeline.py:188} INFO - Missing pipeline option (runner). Executing pipeline using the default runner: DirectRunner.
[2022-03-24 15:42:39,547] {logging_mixin.py:109} INFO - Downloading file in  /opt/***/zip_to_csv
[2022-03-24 15:43:18,043] {logging_mixin.py:109} INFO - Extracting file in  /opt/***/zip_to_csv
[2022-03-24 15:43:26,742] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/tfx/orchestration/airflow/airflow_component.py", line 76, in _airflow_component_launcher
    launcher.launch()
  File "/home/airflow/.local/lib/python3.7/site-packages/tfx/orchestration/launcher/base_component_launcher.py", line 203, in launch
    copy.deepcopy(execution_decision.exec_properties))
  File "/home/airflow/.local/lib/python3.7/site-packages/tfx/orchestration/launcher/in_process_component_launcher.py", line 74, in _run_executor
    copy.deepcopy(input_dict), output_dict, copy.deepcopy(exec_properties))
  File "/home/airflow/.local/lib/python3.7/site-packages/tfx/components/example_gen/base_example_gen_executor.py", line 274, in Do
    example_splits = self.GenerateExamplesByBeam(pipeline, exec_properties)
  File "/home/airflow/.local/lib/python3.7/site-packages/tfx/components/example_gen/base_example_gen_executor.py", line 200, in GenerateExamplesByBeam
    | 'SplitData' >> beam.Partition(_PartitionFn, len(buckets), buckets,
  File "/home/airflow/.local/lib/python3.7/site-packages/apache_beam/transforms/ptransform.py", line 1092, in __ror__
    return self.transform.__ror__(pvalueish, self.label)
  File "/home/airflow/.local/lib/python3.7/site-packages/apache_beam/transforms/ptransform.py", line 614, in __ror__
    result = p.apply(self, pvalueish, label)
  File "/home/airflow/.local/lib/python3.7/site-packages/apache_beam/pipeline.py", line 662, in apply
    return self.apply(transform, pvalueish)
  File "/home/airflow/.local/lib/python3.7/site-packages/apache_beam/pipeline.py", line 708, in apply
    pvalueish_result = self.runner.apply(transform, pvalueish, self._options)
  File "/home/airflow/.local/lib/python3.7/site-packages/apache_beam/runners/runner.py", line 185, in apply
    return m(transform, input, options)
  File "/home/airflow/.local/lib/python3.7/site-packages/apache_beam/runners/runner.py", line 215, in apply_PTransform
    return transform.expand(input)
  File "/home/airflow/.local/lib/python3.7/site-packages/apache_beam/transforms/ptransform.py", line 996, in expand
    return self._fn(pcoll, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/census_consumer_complaint_custom_component/example_gen/remote_zip_csv_example_gen/executor.py", line 63, in _ZipToExample
    os.remove(zip_file_path)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/zip_to_csv/complaints.csv.zip'
[2022-03-24 15:43:26,754] {taskinstance.py:1282} INFO - Marking task as FAILED. dag_id=census_consumer_complaint, task_id=RemoteZipCsvExampleGen, execution_date=20220323T000000, start_date=20220324T154239, end_date=20220324T154326
[2022-03-24 15:43:26,763] {standard_task_runner.py:92} ERROR - Failed to execute job 54 for task RemoteZipCsvExampleGen
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/tfx/orchestration/airflow/airflow_component.py", line 76, in _airflow_component_launcher
    launcher.launch()
  File "/home/airflow/.local/lib/python3.7/site-packages/tfx/orchestration/launcher/base_component_launcher.py", line 203, in launch
    copy.deepcopy(execution_decision.exec_properties))
  File "/home/airflow/.local/lib/python3.7/site-packages/tfx/orchestration/launcher/in_process_component_launcher.py", line 74, in _run_executor
    copy.deepcopy(input_dict), output_dict, copy.deepcopy(exec_properties))
  File "/home/airflow/.local/lib/python3.7/site-packages/tfx/components/example_gen/base_example_gen_executor.py", line 274, in Do
    example_splits = self.GenerateExamplesByBeam(pipeline, exec_properties)
  File "/home/airflow/.local/lib/python3.7/site-packages/tfx/components/example_gen/base_example_gen_executor.py", line 200, in GenerateExamplesByBeam
    | 'SplitData' >> beam.Partition(_PartitionFn, len(buckets), buckets,
  File "/home/airflow/.local/lib/python3.7/site-packages/apache_beam/transforms/ptransform.py", line 1092, in __ror__
    return self.transform.__ror__(pvalueish, self.label)
  File "/home/airflow/.local/lib/python3.7/site-packages/apache_beam/transforms/ptransform.py", line 614, in __ror__
    result = p.apply(self, pvalueish, label)
  File "/home/airflow/.local/lib/python3.7/site-packages/apache_beam/pipeline.py", line 662, in apply
    return self.apply(transform, pvalueish)
  File "/home/airflow/.local/lib/python3.7/site-packages/apache_beam/pipeline.py", line 708, in apply
    pvalueish_result = self.runner.apply(transform, pvalueish, self._options)
  File "/home/airflow/.local/lib/python3.7/site-packages/apache_beam/runners/runner.py", line 185, in apply
    return m(transform, input, options)
  File "/home/airflow/.local/lib/python3.7/site-packages/apache_beam/runners/runner.py", line 215, in apply_PTransform
    return transform.expand(input)
  File "/home/airflow/.local/lib/python3.7/site-packages/apache_beam/transforms/ptransform.py", line 996, in expand
    return self._fn(pcoll, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/census_consumer_complaint_custom_component/example_gen/remote_zip_csv_example_gen/executor.py", line 63, in _ZipToExample
    os.remove(zip_file_path)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/zip_to_csv/complaints.csv.zip'
[2022-03-24 15:43:26,797] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-03-24 15:43:26,824] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
